version: "3.8"

services:
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=${DB_NAME}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PASSWORD}
   web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
         - .:/channel_service_test
      ports:
         - "8000:8000"
      depends_on:
         - db
      env_file:
         - .env

volumes:
   postgres_data: