# Generated by Django 4.0.6 on 2022-07-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.BigIntegerField()),
                ('cost_dol', models.IntegerField()),
                ('cost_rub', models.IntegerField()),
                ('delivery_time', models.DateTimeField()),
            ],
        ),
    ]
