# Generated by Django 4.0.6 on 2022-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_gs_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetsdata',
            name='delivery_time',
            field=models.DateField(),
        ),
    ]
