# Generated by Django 4.0.6 on 2022-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_gs_data_app', '0002_alter_sheetsdata_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetsdata',
            name='delivery_time',
            field=models.CharField(max_length=50),
        ),
    ]
