# Generated by Django 4.0.6 on 2022-07-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_gs_data_app', '0003_alter_sheetsdata_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetsdata',
            name='cost_dol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sheetsdata',
            name='cost_rub',
            field=models.FloatField(),
        ),
    ]
