# Generated by Django 4.0.6 on 2022-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_gs_data_app', '0004_alter_sheetsdata_cost_dol_alter_sheetsdata_cost_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetsdata',
            name='cost_dol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sheetsdata',
            name='cost_rub',
            field=models.IntegerField(),
        ),
    ]
